name: Laravel

on:
  push:
    branches: [ "main", "development", "test/all-test" ]
  pull_request:
    branches: [ "main", "development", "test/all-test" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: presentia_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'

    - uses: actions/checkout@v4
  
    - name: Force Copy .env.testing
      run: |
        cp presentia-backend/.env.testing presentia-backend/.env

    - name: Install Dependencies
      run: |
        cd presentia-backend
        composer install --no-progress --no-interaction --prefer-dist

    - name: Copy .env if not exists
      run: |
        if [ ! -f presentia-backend/.env ]; then
          cp presentia-backend/.env.testing presentia-backend/.env;
        fi

    - name: Generate key
      run: |
        cd presentia-backend
        php artisan key:generate

    - name: Directory Permissions
      run: |
        cd presentia-backend
        chmod -R 777 storage bootstrap/cache

    - name: Wait for MySQL
      run: sleep 10s

    - name: Run migrations
      run: |
        cd presentia-backend
        php artisan migrate --force

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: presentia_test
        DB_USERNAME: user
        DB_PASSWORD: password
      run: |
        cd presentia-backend
        php artisan test